---
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'debian/**'
    branches:
      - master
  pull_request:
    paths-ignore:
      - 'debian/**'
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - id: cache-ccache
        uses: hendrikmuhs/ccache-action@v1
        with:
          key: ${{ matrix.os }}-${{ matrix.type }}

      - name: Install dependencies
        run: |
          sudo apt install -y --no-install-recommends \
            meson \
            libavahi-client-dev \
            libsystemd-dev

      - name: Configure
        run: |
          meson setup \
            -Dauto_features=enabled \
             --force-fallback-for=fmt \
            -Dwrap_mode=nofallback \
            output

      - name: Build
        run: ninja -C output -v
